"""empty message

Revision ID: 88a5b40a14dc
Revises: 74b9a6ad876c
Create Date: 2022-04-08 13:22:53.943001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a5b40a14dc'
down_revision = '74b9a6ad876c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('chore', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('completed_by', sa.String(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chores')
    # ### end Alembic commands ###
